
sudo: required
language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - node_modules
services:
  - mongodb
  - docker

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g gulp-cli codecov

script:
  - npm run cover || travis_terminate 1;

after_success:
  - codecov --token=${CODECOV_TOKEN}

deploy:
  - provider: script
    script: bash .travis/docker-deploy.sh
    on:
      branch: develop
  - provider: script
    script: bash .travis/docker-deploy.sh
    on:
      tags: true
  - provider: codedeploy
    bucket: "phc-codedeploy-essentials-codedeploys3bucket-jumhvxvmnql0"
    key: deploy.zip
    bundle_type: zip
    access_key_id: "${CODEDEPLOY_ACCESS_KEY_ID}"
    secret_access_key: "${CODEDEPLOY_SECRET_ACCESS_KEY}"
    application: "phc-codedeploy-CodeDeployApplication-1JIG4ADRRDKT4"
    deployment_group: "phc-codedeploy-DeploymentGroup-3DWDGW9ASVEZ"
    region: "us-east-1"
    on:
      branch: develop
