
sudo: required
language: node_js
node_js:
  - 10.15.3
cache:
  directories:
    - node_modules
services:
  - mongodb
  - docker

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
  - npm install -g gulp-cli
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" = "develop" ]; then docker pull "${IMAGE_NAME}:develop" || true ; fi

script:
  - npm test || travis_terminate 1;
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" = "develop" ]; then docker build -f Dockerfile --pull --cache-from "${IMAGE_NAME}:develop" --tag "${IMAGE_NAME}" . ; fi

before_deploy:
  - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASS}" "${REGISTRY_SERVER}"
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:develop"
  - docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${git_sha}-develop"

deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:develop" && docker push "${IMAGE_NAME}:${git_sha}-develop"
    on:
      branch: develop
  # - provider: codedeploy
  #   revision_type: github
  #   access_key_id: "${ACCESS_KEY_ID}"
  #   secret_access_key: "${SECRET_ACCESS_KEY}"
  #   application: "phccp-autodeploy"
  #   deployment_group: "phccp-autodeploy-group"
  #   region: "us-east-1"
  #   on:
  #     branch: develop
