version: '3.2'

services:
  phccp:
    build:
        context: .
        dockerfile: Dockerfile
    image: phccp
    container_name: phccp
    ports:
        - 443:443
    environment:
        NODE_ENV: production
        PORT: 443
        DOMAIN: https://dev.phc.sagesandbox.org
        APP_INIT_ADMIN_EMAIL: thomas.schaffter@sagebase.org
        APP_INIT_ADMIN_PASSWORD: admin
        MONGODB_URI: mongodb://mongo-prod:27017/phccp
        MONGODB_USER: app
        MONGODB_PASSWORD: app123
        MONGODB_SSL: 'true'
        MONGODB_SSL_VALIDATE: 'false'  # Set to false when using self-signed certificate
        # MONGODB_SSL_CA:  # Content of CA's certificate (not the path)
        # MONGODB_SSL_KEY: # Content of the key (default: read ./certs/server.key)
        # MONGODB_SSL_CERT:  # Content of the certificate (default: read ./certs/server.cert)
        # Enabling Google OAuth 2.0
        OAUTH_GOOGLE_ID:
        OAUTH_GOOGLE_SECRET:
        # Enabling Google SAML
        SAML_GOOGLE_ENTRY_POINT:
        SAML_GOOGLE_ISSUER:
        # Enabling Microsoft Azure AD OpenID Connect (demo)
        AZUREAD_OPENIDCONNECT_IDENTITY_METADATA:
        AZUREAD_OPENIDCONNECT_CLIENT_ID:
        # Enabling Roche Azure AD
        ROCHE_AZURE_AD_IDENTITY_METADATA:
        ROCHE_AZURE_AD_CLIENT_ID:
        ROCHE_AZURE_AD_CLIENT_SECRET:
        # Provenance service
        PROVENANCE_API_SERVER_URL: http://phccp-prov:8080/rest/v1
    volumes:
        - ./certs/server.key:/usr/src/app/certs/server.key:ro
        - ./certs/server.cert:/usr/src/app/certs/server.cert:ro
    depends_on:
        - mongo-prod
        - phccp-prov

  phccp-neo4j:
    image: docker.synapse.org/syn18489221/phccp-neo4j
    container_name: phccp-neo4j
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j-username/neo4j-password
    volumes:
      - /tmp/neo4j/data:/var/lib/neo4j/data
      - /tmp/neo4j/logs:/logs

  phccp-prov:
    image: docker.synapse.org/syn18489221/prov-service:develop
    command: python3 -m synprov
    container_name: phccp-prov
    ports:
      - 8080:8080
    environment:
      NEO4J_SCHEME: bolt
      NEO4J_HOST: phccp-neo4j
      NEO4J_PORT: 7687
      NEO4J_USERNAME: neo4j-username
      NEO4J_PASSWORD: neo4j-password
      FLASK_HOST: "0.0.0.0"
    links:
      - phccp-neo4j

  mongo-prod:
    image: docker.synapse.org/syn18489221/phccp-mongo
    command: mongod --port 27017 --sslMode requireSSL --sslPEMKeyFile /etc/ssl/mongodb.pem
    container_name: mongo-prod
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        # Adding app user
        MONGO_INITDB_DATABASE: phccp
        MONGO_USERNAME: app
        MONGO_PASSWORD: app123
    volumes:
        - ./certs/mongodb.pem:/etc/ssl/mongodb.pem:ro
        # - ./mongodb:/data/db
