version: '3.2'

services:
  phccp:
    build: .
    image: phc-collaboration-portal
    # image: docker.synapse.org/syn18489221/phc-collaboration-portal:v0.2
    container_name: phccp
    environment:
        NODE_ENV: production
        PORT: '8080'
        MONGODB_URI: 'mongodb://mongo:27017/phccp'
        DOMAIN: 'http://phc.sagesandbox.org'
        GOOGLE_ID: '<GOOGLE_ID>'
        GOOGLE_SECRET: '<GOOGLE_SECRET>'
    ports:
        - '80:8080'
    depends_on:
        - mongo

  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
        - '27017:27017'
    #volumes:
    #    - mongo-data:/data/db
    #deploy:
    #    placement:
    #        constraints:
    #            - node.role == manager

    #volumes:
    #    mongo-data:
