version: '2'
services:
  phccp:
    build: .
    container_name: 'phccp'
    ports:
        - 8080:8080
    links:
        - mongo
    depends_on:
        - mongo
  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
        - 27017:27017
