version: '3.2'

services:
  phccp-webpack-dev-server:
    build:
        context: .
        dockerfile: Dockerfile.dev
    image: phccp-webpack-dev-server
    command: npm run start:client
    container_name: phccp-webpack-dev-server
    ports:
        - 443:443
    environment:
        NODE_ENV: development
        CLIENT_PORT: 443
        IP: phccp-dev-server
    depends_on:
        - phccp-dev-server

  phccp-dev-server:
    build:
        context: .
        dockerfile: Dockerfile.dev
    image: phccp-dev-server
    command: npm run start:server
    container_name: phccp-dev-server
    ports:
        - 9000:9000
    environment:
        NODE_ENV: development
        DOMAIN: https://dev.phc.sagesandbox.org
        APP_INIT_ADMIN_EMAIL: thomas.schaffter@sagebase.org
        APP_INIT_ADMIN_PASSWORD: admin
        MONGODB_URI: mongodb://mongo-dev:27017/phccp-dev
        MONGODB_USER: app
        MONGODB_PASSWORD: app123
        MONGODB_SSL: 'true'
        MONGODB_SSL_VALIDATE: 'false'  # Set to false when using self-signed certificate
        # MONGODB_SSL_CA:  # Content of CA's certificate (not the path)
        # MONGODB_SSL_KEY: # Content of the key (default: read ./certs/server.key)
        # MONGODB_SSL_CERT:  # Content of the certificate (default: read ./certs/server.cert)
        # Enabling Google OAuth 2.0
        OAUTH_GOOGLE_ID:
        OAUTH_GOOGLE_SECRET:
        # Enabling Google SAML
        SAML_GOOGLE_ENTRY_POINT:
        SAML_GOOGLE_ISSUER:
        # Enabling Microsoft Azure AD OpenID Connect (demo)
        AZUREAD_OPENIDCONNECT_IDENTITY_METADATA:
        AZUREAD_OPENIDCONNECT_CLIENT_ID:
        # Enabling Roche Azure AD
        ROCHE_AZURE_AD_IDENTITY_METADATA:
        ROCHE_AZURE_AD_CLIENT_ID:
        ROCHE_AZURE_AD_CLIENT_SECRET:
    depends_on:
        - mongo-dev

  mongo-dev:
    build:
        context: ./mongo
        dockerfile: Dockerfile
    image: mongo-phccp
    command: mongod --port 27017 --sslMode requireSSL --sslPEMKeyFile /etc/ssl/mongodb.pem
    container_name: mongo-dev
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        # Adding app user
        MONGO_INITDB_DATABASE: phccp-dev
        MONGO_USERNAME: app
        MONGO_PASSWORD: app123
    volumes:
        - ./certs/mongodb.pem:/etc/ssl/mongodb.pem
        # - ./mongodb:/data/db
