version: '3'
services:
  phccp:
    build: .
    image: phccp
    container_name: 'phccp'
    environment:
        MONGODB_URI: 'mongodb://mongo:27017/phccp'
    ports:
        - '80:8080'
    depends_on:
        - mongo
  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
        - '27017:27017'
