/* global require, process */

import gulp from 'gulp';
import del from 'del';
import dotenv from 'dotenv';
import fs from 'fs';
import { union, map } from 'lodash';
import log from 'fancy-log';
import * as colors from 'ansi-colors';
import webpack from 'webpack';
import makeWebpackConfig from './webpack.make';
import lazypipe from 'lazypipe';
import nodemon from 'nodemon';
import through2 from 'through2';

import path from 'path';
import gulpLoadPlugins from 'gulp-load-plugins';
import http from 'http';
import open from 'open';
import { Server as KarmaServer } from 'karma';
import { protractor, webdriver_update } from 'gulp-protractor';

var plugins = gulpLoadPlugins();
var config;

const clientPath = 'client';
const serverPath = 'server';
const configPath = 'config';
const paths = {
    client: {
        assets: `${clientPath}/assets/**/*`,
        images: `${clientPath}/assets/images/**/*`,
        revManifest: `${clientPath}/assets/rev-manifest.json`,
        scripts: [`${clientPath}/**/!(*.spec|*.mock).ts`],
        styles: [`${clientPath}/{app,components}/**/*.scss`],
        mainStyle: `${clientPath}/app/app.scss`,
        views: `${clientPath}/{app,components}/**/*.html`,
        mainView: `${clientPath}/app.html`,
        test: [`${clientPath}/{app,components}/**/*.{spec,mock}.ts`],
        e2e: ['e2e/**/*.spec.js'],
    },
    server: {
        scripts: [`${serverPath}/**/!(*.spec|*.integration|*.mock).js`, `!${serverPath}/config/local.env.sample.js`],
        json: [`${serverPath}/{,**/}*.json`],
        // swagger: [`${serverPath}/swagger/**/*.yaml`],
        test: {
            integration: [`${serverPath}/**/*.integration.js`, 'mocha.global.js'],
            unit: [`${serverPath}/**/*.spec.js`, 'mocha.global.js'],
        },
    },
    karma: 'karma.conf.js',
    dist: 'dist', // used
    config: {
        default: `${configPath}/default.env`,
        development: `${configPath}/development.env`,
        production: `${configPath}/production.env`,
        serverSslCert: `${configPath}/certs/server.cert`,
        serverSslKey: `${configPath}/certs/server.key`,
        serverSslCA: '',
        mongodbSslCert: `${configPath}/certs/server.cert`, // here reused server cert for simplicity
        mongodbSslKey: `${configPath}/certs/server.key`, // here reused server key for simplicity
        mongodbSslCA: '',
    },
};

/********************
 * Helper functions
 ********************/

/**
 * Sets the env vars stored in the .env file specified.
 * @param {*} envFile
 */
const readConfig = envFile => {
    // https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set
    // eslint-disable-next-line no-sync
    const envConfig = dotenv.parse(fs.readFileSync(envFile));
    for (const k in envConfig) {
        process.env[k] = envConfig[k];
    }
};

/**
 * Processes a log message generated by the server.
 * @param {*} msg
 */
const onServerLog = msg => {
    log(colors.white('[') + colors.yellow('nodemon') + colors.white('] ') + msg.message); // was console.log()
};

function checkAppReady(cb) {
    var options = {
        host: 'localhost',
        port: config.port,
    };
    http.get(options, () => cb(true)).on('error', () => cb(false));
}

// Call page until first success
function whenServerReady(cb) {
    var serverReady = false;
    var appReadyInterval = setInterval(
        () =>
            checkAppReady(ready => {
                if (!ready || serverReady) {
                    return;
                }
                clearInterval(appReadyInterval);
                serverReady = true;
                cb();
            }),
        100
    );
}

/********************
 * Reusable pipelines
 ********************/

// About lazypipe and Gulp 4
// https://stackoverflow.com/a/40101404

let lintClientScripts = lazypipe()
    .pipe(
        plugins.tslint,
        {
            formatter: 'verbose',
        }
    )
    .pipe(
        plugins.tslint.report,
        {
            emitError: false,
        }
    );

const lintClientTestScripts = lazypipe()
    .pipe(
        plugins.tslint,
        {
            formatter: 'verbose',
        }
    )
    .pipe(
        plugins.tslint.report,
        {
            emitError: false,
        }
    );

/**
 * Lints the server scripts.
 */
const lintServerScripts = lazypipe()
    .pipe(
        plugins.eslint,
        `${serverPath}/.eslintrc`
    )
    .pipe(plugins.eslint.format);

/**
 * Lints the server test scripts.
 */
const lintServerTestScripts = lazypipe()
    .pipe(
        plugins.eslint,
        {
            configFile: `${serverPath}/.eslintrc`,
            envs: ['node', 'es6', 'mocha'],
        }
    )
    .pipe(plugins.eslint.format);

/**
 * Transpiles the server files.
 */
let transpileServer = lazypipe()
    .pipe(plugins.sourcemaps.init)
    .pipe(
        plugins.babel, // reads .babelrc
        {
            presets: ['@babel/preset-env'],
            plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-transform-runtime'],
        }
    )
    .pipe(
        plugins.sourcemaps.write,
        '.'
    );

let mocha = lazypipe().pipe(
    plugins.mocha,
    {
        reporter: 'spec',
        timeout: 5000,
        require: ['./mocha.conf'],
    }
);

// let istanbul = lazypipe()
//     .pipe(plugins.istanbul.writeReports)
//     .pipe(plugins.istanbulEnforcer, {
//         thresholds: {
//             global: {
//                 lines: 80,
//                 statements: 80,
//                 branches: 80,
//                 functions: 80
//             }
//         },
//         coverageDirectory: './coverage',
//         rootDirectory: ''
//     });

/********************
 * Env
 ********************/

/**
 * Sets the default env vars.
 */
gulp.task('env:default', done => {
    readConfig(paths.config.default);
    done();
});

/**
 * Sets the env vars specific to the test environment.
 */
gulp.task('env:test', done => {
    process.env.NODE_ENV = 'test';
    done();
});

/**
 * Sets the env vars specific to the production environment.
 */
gulp.task('env:prod', done => {
    readConfig(paths.config.production);
    process.env.NODE_ENV = 'production';
    done();
});

/**
 * Sets the server SSL certificate, key, and certificate authority.
 */
gulp.task('env:ssl:server', done => {
    // eslint-disable-next-line no-sync
    process.env.SSL_CERT = fs.readFileSync(paths.config.serverSslCert);
    // eslint-disable-next-line no-sync
    process.env.SSL_KEY = fs.readFileSync(paths.config.serverSslKey);
    // eslint-disable-next-line no-sync
    process.env.SSL_CA = paths.config.serverSslCA ? fs.readFileSync(paths.config.serverSslCA) : '';
    done();
});

/**
 * Sets the MongoDB SSL certificate, key, and certificate authority.
 */
gulp.task('env:ssl:mongodb', done => {
    // eslint-disable-next-line no-sync
    process.env.MONGODB_SSL_CERT = paths.config.mongodbSslCert ? fs.readFileSync(paths.config.mongodbSslCert) : '';
    // eslint-disable-next-line no-sync
    process.env.MONGODB_SSL_KEY = paths.config.mongodbSslKey ? fs.readFileSync(paths.config.mongodbSslKey) : '';
    // eslint-disable-next-line no-sync
    process.env.MONGODB_SSL_CA = paths.config.mongodbSslCA ? fs.readFileSync(paths.config.mongodbSslCA) : '';
    done();
});

/**
 * Sets the SSL certificates and keys.
 */
gulp.task('env:ssl', gulp.series('env:ssl:server', 'env:ssl:mongodb'));

/********************
 * Clean tasks
 ********************/

/**
 * Removes the content of the dist folder.
 */
gulp.task('clean:dist', () =>
    del([`${paths.dist}/!(.git*|.openshift)**`], {
        dot: true,
    })
);

/**
 * Removes the content of the .tmp folder.
 */
gulp.task('clean:tmp', () =>
    del(['.tmp/**/*'], {
        dot: true,
    })
);

/********************
 * Tasks
 ********************/

/**
 * Injects the style filenames into the client main style file.
 */
// TODO This tasks reports: gulp-inject Nothing to inject into app.scss
gulp.task('inject:scss', () =>
    gulp
        .src(paths.client.mainStyle)
        .pipe(
            plugins.inject(
                gulp
                    .src(union(paths.client.styles, [`!${paths.client.mainStyle}`]), {
                        read: false,
                    })
                    .pipe(plugins.sort()),
                {
                    transform: filepath => {
                        let newPath = filepath
                            .replace(`/${clientPath}/app/`, '')
                            .replace(`/${clientPath}/components/`, '../components/')
                            // eslint-disable-next-line no-unused-vars
                            .replace(/_(.*).scss/, (match, p1, offset, string) => p1) // TODO: Remove theme files?
                            .replace('.scss', '');
                        return `@import '${newPath}';`;
                    },
                }
            )
        )
        .pipe(gulp.dest(`${clientPath}/app`))
);

/**
 * Injects content into files.
 */
gulp.task('inject', gulp.series('inject:scss'));

/**
 * Compiles the app using webpack.
 * @param {*} options
 * @param {*} cb
 */
const webpackCompile = (options, cb) => {
    let compiler = webpack(makeWebpackConfig(options));

    compiler.run((err, stats) => {
        if (err) return cb(err);

        log(
            stats.toString({
                colors: true,
                timings: true,
                chunks: options.BUILD,
            })
        );
        cb();
    });
};

/**
 * Builds the app with webpack for development.
 */
gulp.task('webpack:dev', cb =>
    webpackCompile(
        {
            DEV: true,
        },
        cb
    )
);

/**
 * Builds the app with webpack for production.
 */
gulp.task('webpack:dist', cb =>
    webpackCompile(
        {
            BUILD: true,
        },
        cb
    )
);

/**
 * Builds the app with webpack for testing.
 */
gulp.task('webpack:test', cb =>
    webpackCompile(
        {
            TEST: true,
        },
        cb
    )
);

gulp.task('styles', () =>
    gulp
        .src(paths.client.mainStyle)
        .pipe(styles())
        .pipe(gulp.dest('.tmp/app'))
);

/**
 * Transpiles the server files.
 */
gulp.task('transpile:server', () => {
    var toTranspile = union(paths.server.scripts, paths.server.json);
    return gulp
        .src(toTranspile)
        .pipe(transpileServer())
        .pipe(gulp.dest(`${paths.dist}/${serverPath}`));
});

gulp.task('lint:client', cb =>
    gulp
        .src(union(paths.client.scripts, map(paths.client.test, blob => `!${blob}`)))
        .pipe(lintClientScripts())
        .on('end', cb)
);

/**
 * Lints the server scripts.
 */
gulp.task('lint:server', done =>
    gulp
        .src(union(paths.server.scripts, map(paths.server.test, blob => `!${blob}`)))
        .pipe(lintServerScripts())
        .on('end', done)
);

gulp.task('lint', gulp.parallel('lint:client', 'lint:server'));

/**
 * Lints the server test scripts.
 */
gulp.task('lint:server:test', done =>
    gulp
        .src(union(paths.server.test.integration, paths.server.test.unit))
        .pipe(lintServerTestScripts())
        .on('end', done)
);

gulp.task('jscs', () =>
    gulp
        .src(union(paths.client.scripts, paths.server.scripts))
        .pipe(plugins.jscs())
        .pipe(plugins.jscs.reporter())
);

gulp.task('start:client', cb =>
    require('./webpack.server')
        .start(config.clientPort)
        .then(() => {
            open(`http://localhost:${config.clientPort}`);
            cb();
        })
);

gulp.task('start:server', () => {
    process.env.NODE_ENV = process.env.NODE_ENV || 'development';
    config = require(`./${serverPath}/config/environment`);
    nodemon(`-w ${serverPath} ${serverPath}`).on('log', onServerLog);
});

/**
 * Starts the server in production environment.
 */
gulp.task('start:server:prod', () => {
    process.env.NODE_ENV = process.env.NODE_ENV || 'production';
    config = require(`./${paths.dist}/${serverPath}/config/environment`);
    nodemon(`-w ${paths.dist}/${serverPath} ${paths.dist}/${serverPath}`).on('log', onServerLog);
});

gulp.task('start:server:debug', () => {
    process.env.NODE_ENV = process.env.NODE_ENV || 'development';
    config = require(`./${serverPath}/config/environment`);
    // nodemon(`-w ${serverPath} --debug=5858 --debug-brk ${serverPath}`)
    nodemon(`-w ${serverPath} --inspect --debug-brk ${serverPath}`).on('log', onServerLog);
});

gulp.task('watch', () => {
    var testFiles = union(paths.client.test, paths.server.test.unit, paths.server.test.integration);

    plugins
        .watch(union(paths.server.scripts, testFiles))
        .pipe(plugins.plumber())
        .pipe(lintServerScripts());

    plugins
        .watch(union(paths.server.test.unit, paths.server.test.integration))
        .pipe(plugins.plumber())
        .pipe(lintServerTestScripts());
});

gulp.task('mocha:unit', () => gulp.src(paths.server.test.unit).pipe(mocha()));

gulp.task('mocha:integration', () => gulp.src(paths.server.test.integration).pipe(mocha()));

gulp.task('test:server', gulp.series(/*'env:all',*/ 'env:test', 'mocha:unit', 'mocha:integration'));

// gulp.task('coverage:pre', () => {
//     return gulp.src(paths.server.scripts)
//         // Covering files
//         .pipe(plugins.istanbul({
//             // instrumenter: Instrumenter, // Use the isparta instrumenter (code coverage for ES6)
//             includeUntested: true
//         }));
//         // Force `require` to return covered files
//         // .pipe(plugins.istanbul.hookRequire());
// });

// gulp.task('coverage:unit', () => {
//     return gulp.src(paths.server.test.unit)
//         .pipe(mocha())
//         .pipe(istanbul())
//     // Creating the reports after tests ran
// });

// gulp.task('coverage:integration', () => {
//     return gulp.src(paths.server.test.integration)
//         .pipe(mocha())
//         .pipe(istanbul())
//     // Creating the reports after tests ran
// });

// gulp.task('test:server:coverage', cb =>
//     gulp.series(
//         'coverage:pre',
//         // 'env:all',
//         // 'env:test',
//         // 'coverage:unit',
//         // 'coverage:integration',
//         cb
//     ));

// Downloads the selenium webdriver
gulp.task('webdriver_update', webdriver_update);

gulp.task(
    'test:e2e',
    gulp.series(gulp.parallel('webpack:dist', /*'env:all',*/ 'env:test', 'start:server', 'webdriver_update'), () => {
        gulp.src(paths.client.e2e)
            .pipe(
                protractor({
                    configFile: 'protractor.conf.js',
                })
            )
            .on('error', e => {
                throw e;
            })
            .on('end', () => {
                process.exit();
            });
    })
);

gulp.task('test:client', done => {
    new KarmaServer(
        {
            configFile: `${__dirname}/${paths.karma}`,
            singleRun: true,
        },
        err => {
            done(err);
            process.exit(err);
        }
    ).start();
});

gulp.task('test', gulp.series('test:server', 'test:client'));

/********************
 * Build
 ********************/

/**
 * Optimizes the images and adds static asset revisioning by appending content
 * hash to filenames.
 */
gulp.task('build:images', () =>
    gulp
        .src(paths.client.images)
        .pipe(
            plugins.imagemin([
                plugins.imagemin.optipng({
                    optimizationLevel: 5,
                }),
                plugins.imagemin.jpegtran({
                    progressive: true,
                }),
                plugins.imagemin.gifsicle({
                    interlaced: true,
                }),
                plugins.imagemin.svgo({
                    plugins: [
                        {
                            removeViewBox: false,
                        },
                    ],
                }),
            ])
        )
        .pipe(plugins.rev())
        .pipe(gulp.dest(`${paths.dist}/${clientPath}/assets/images`))
        .pipe(
            plugins.rev.manifest(`${paths.dist}/${paths.client.revManifest}`, {
                base: `${paths.dist}/${clientPath}/assets`,
                merge: true,
            })
        )
        .pipe(gulp.dest(`${paths.dist}/${clientPath}/assets`))
);

/**
 * Rewrites occurrences of filenames which have been renamed by gulp-rev.
 */
gulp.task('revReplaceWebpack', function () {
    return gulp
        .src('dist/**/*.js')
        .pipe(
            plugins.revReplace({
                manifest: gulp.src(`${paths.dist}/${paths.client.revManifest}`),
            })
        )
        .pipe(gulp.dest('dist'));
});

/**
 * Copies extra files such as favicon.ico, robots.txt, and .htaccess to the dist folder.
 */
gulp.task('copy:extras', () =>
    gulp
        .src([`${clientPath}/favicon.ico`, `${clientPath}/robots.txt`, `${clientPath}/.htaccess`], {
            dot: true,
        })
        .pipe(gulp.dest(`${paths.dist}/${clientPath}`))
);

/**
 *
 *
 * Example: turns 'bootstrap/fonts/font.woff' into 'bootstrap/font.woff'.
 */
const flatten = () =>
    through2.obj(function (file, enc, next) {
        if (!file.isDirectory()) {
            try {
                let dir = path.dirname(file.relative).split(path.sep)[0];
                let fileName = path.normalize(path.basename(file.path));
                file.path = path.join(file.base, path.join(dir, fileName));
                // eslint-disable-next-line no-invalid-this
                this.push(file);
            } catch (e) {
                // eslint-disable-next-line no-invalid-this
                this.emit('error', new Error('Unable to flatten filename', e));
            }
        }
        next();
    });

/**
 * Copies fonts to assets/fonts in development environment.
 */
gulp.task('copy:fonts:dev', () =>
    gulp
        .src('node_modules/{font-awesome}/fonts/*')
        .pipe(flatten())
        .pipe(gulp.dest(`${clientPath}/assets/fonts`))
);

/**
 * Copies fonts to assets/fonts when building the app.
 */
gulp.task('copy:fonts:dist', () =>
    gulp
        .src('node_modules/{font-awesome}/fonts/*')
        .pipe(flatten())
        .pipe(gulp.dest(`${paths.dist}/${clientPath}/assets/fonts`))
);

gulp.task(
    'serve',
    gulp.series(
        gulp.parallel(
            'clean:tmp',
            'lint',
            'inject'
            // 'copy:fonts:dev',
            /*'env:all',*/
        ),
        // 'webpack:dev',
        gulp.parallel('start:server', 'start:client'),
        'watch'
    )
);

gulp.task('serve:debug', cb =>
    gulp.series(
        gulp.parallel(
            'clean:tmp',
            'lint',
            'inject'
            // 'copy:fonts:dev',
            /*'env:all',*/
        ),
        'webpack:dev',
        gulp.parallel('start:server:debug', 'start:client'),
        'watch',
        cb
    )
);

/**
 * Copies the client assets but the images to the dist folder.
 */
gulp.task('copy:assets', () =>
    gulp.src([paths.client.assets, `!${paths.client.images}`]).pipe(gulp.dest(`${paths.dist}/${clientPath}/assets`))
);

/**
 * Copies the files required to run the server.
 */
gulp.task('copy:server', () => {
    var serverFiles = ['package.json'];
    return gulp
        .src(serverFiles, {
            cwdbase: true,
        })
        .pipe(gulp.dest(paths.dist));
});

/**
 * Builds the app for distribution.
 */
gulp.task(
    'build',
    gulp.series(
        gulp.parallel('clean:dist', 'clean:tmp'),
        'inject',
        'transpile:server',
        'build:images',
        gulp.parallel('copy:extras', 'copy:assets', /*'copy:fonts:dist',*/ 'copy:server'),
        // TODO do we need all the font put in dist/client/?
        // TODO Investigate @babel/preset-env: `DEBUG` option (tsconfig.json)?
        'webpack:dist',
        'revReplaceWebpack'
    )
);

/**
 * Starts the distribution server in production environment.
 */
gulp.task(
    'serve:dist',
    gulp.series('env:default', 'env:prod', 'env:ssl', 'start:server:prod') // gulp.parallel('start:server:prod', 'start:client')
);

/********************
 * Default task
 ********************/

gulp.task('default', gulp.series('build'));
